import type { CourseDefinition } from '../../game/course/courseDefinition';
import { COURSES } from './courseIds';

const summary = COURSES.find((course) => course.id === 'blacksmoker-run');
if (!summary) throw new Error('Missing Blacksmoker Run course metadata.');

const blacksmokerRun = {
  version: 1,
  courseId: summary.id,
  name: summary.name,
  summary: summary.summary,
  medalTimesMs: { gold: 34_000, silver: 52_000, bronze: 75_000 },
  visuals: {
    kind: 'gltf',
    visualAsset: 'courses/blacksmoker-run.visual.glb',
    collisionAsset: 'courses/blacksmoker-run.collision.glb',
    waterColor: '#102b3a',
    seabedColor: '#293c46',
  },
  spawn: { position: [0, -5, 0], yaw: 0 },
  checkpoints: [
    {
      id: 'smoker-entry',
      position: [0, -5, 16],
      radius: 3.5,
      direction: [0, 0, 1],
    },
    {
      id: 'smoker-east-descent',
      position: [7, -7, 48],
      radius: 3.5,
      direction: [0, 0, 1],
    },
    {
      id: 'smoker-deep-crossing',
      position: [-7, -9, 88],
      radius: 3.5,
      direction: [0, 0, 1],
    },
    {
      id: 'smoker-updraft',
      position: [6, -6, 126],
      radius: 3.5,
      direction: [0, 0, 1],
    },
    {
      id: 'smoker-last-turn',
      position: [-6, -8, 166],
      radius: 3.5,
      direction: [0, 0, 1],
    },
    {
      id: 'smoker-finish',
      position: [0, -5, 208],
      radius: 3.5,
      direction: [0, 0, 1],
    },
  ],
  pearls: [
    { id: 'smoker-pearl-entry', position: [0, -5, 24], radius: 0.4 },
    { id: 'smoker-pearl-east', position: [7, -7, 56], radius: 0.4 },
    { id: 'smoker-pearl-deep', position: [-7, -9, 96], radius: 0.4 },
    { id: 'smoker-pearl-rise', position: [6, -6, 134], radius: 0.4 },
    { id: 'smoker-pearl-west', position: [-6, -8, 174], radius: 0.4 },
    { id: 'smoker-pearl-home', position: [0, -5, 200], radius: 0.4 },
  ],
  objects: [
    {
      type: 'box',
      id: 'smoker-seabed',
      position: [0, -16, 106],
      halfExtents: [27, 3, 116],
      rotation: [0, 0, 0, 1],
      collision: 'environment',
      color: '#293c46',
    },
    {
      type: 'box',
      id: 'smoker-west-wall',
      position: [-17, -9, 70],
      halfExtents: [3, 4, 34],
      rotation: [0, 0, 0, 1],
      collision: 'environment',
      color: '#1e303b',
    },
    {
      type: 'box',
      id: 'smoker-east-wall',
      position: [17, -9, 154],
      halfExtents: [3, 4, 34],
      rotation: [0, 0, 0, 1],
      collision: 'environment',
      color: '#1e303b',
    },
    {
      type: 'sphere',
      id: 'smoker-west-root',
      position: [-13, -10, 36],
      radius: 2.5,
      collision: 'environment',
      color: '#394d54',
    },
    {
      type: 'sphere',
      id: 'smoker-east-root',
      position: [13, -10, 184],
      radius: 2.5,
      collision: 'environment',
      color: '#394d54',
    },
    {
      type: 'box',
      id: 'smoker-west-chimney',
      position: [-13, -9, 84],
      halfExtents: [1.5, 4, 1.5],
      rotation: [0, 0, 0, 1],
      collision: 'environment',
      color: '#354049',
    },
    {
      type: 'box',
      id: 'smoker-east-chimney',
      position: [13, -9, 142],
      halfExtents: [1.5, 4, 1.5],
      rotation: [0, 0, 0, 1],
      collision: 'environment',
      color: '#354049',
    },
    {
      type: 'sphere',
      id: 'smoker-hot-vent',
      position: [3, -11, 110],
      radius: 1.2,
      collision: 'hazard',
      color: '#d46f4e',
    },
    {
      type: 'sphere',
      id: 'smoker-cinder-vent',
      position: [-3, -10, 174],
      radius: 1.2,
      collision: 'hazard',
      color: '#d46f4e',
    },
    {
      type: 'current',
      id: 'smoker-west-updraft',
      position: [0, -8, 72],
      halfExtents: [7, 4, 11],
      velocity: [-1.3, 0.5, 0.2],
      color: '#7da9b4',
    },
    {
      type: 'current',
      id: 'smoker-east-updraft',
      position: [0, -7, 149],
      halfExtents: [7, 4, 10],
      velocity: [1.4, 0.4, -0.1],
      color: '#7da9b4',
    },
    {
      type: 'current',
      id: 'smoker-home-updraft',
      position: [0, -6, 192],
      halfExtents: [5, 4, 8],
      velocity: [0, 0.6, 0.5],
      color: '#7da9b4',
    },
    {
      type: 'rotating-gate',
      id: 'smoker-descent-gate',
      position: [-8, -8, 74],
      halfExtents: [3.5, 0.2, 0.2],
      axis: [0, 0, 1],
      phase: 0.9,
      angularSpeed: 0.6,
      color: '#c69058',
    },
    {
      type: 'rotating-gate',
      id: 'smoker-updraft-gate',
      position: [8, -7, 149],
      halfExtents: [4, 0.2, 0.2],
      axis: [0, 0, 1],
      phase: 1.4,
      angularSpeed: -0.45,
      color: '#c69058',
    },
    {
      type: 'rotating-gate',
      id: 'smoker-home-gate',
      position: [-5, -6, 191],
      halfExtents: [3.25, 0.2, 0.2],
      axis: [0, 0, 1],
      phase: 0.3,
      angularSpeed: 0.35,
      color: '#c69058',
    },
  ],
} satisfies CourseDefinition;

export default blacksmokerRun;
